services:
   #kamailio_database:
     #build:
      #context: ./mariadb
      #dockerfile: mariadb.dockerfile
     #environment:
      # - MARIADB_ROOT_PASSWORD=notkamailio
      # - MARIADB_DATABASE=kamailio
      # - MARIADB_USER=kamailio
      # - MARIADB_PASSWORD=kamailiorw
   asterisk:
     build:
      context: ./asterisk
      dockerfile: asterisk.dockerfile
     deploy:
       mode: replicated
       replicas: 6
     #ports:
      # - "5061:5061/udp"
   kamailio_dispatcher:
     depends_on:
       - asterisk
       - kamailio_pg
     build:
      context: ./kamailio
      dockerfile: kamailio.dockerfile
     volumes:
      - ./kamailio/etc:/etc/kamailio
     ports:
       - "5060:5060/udp"
     restart: always
   kamailio_pg:
     build:
      context: ./postgresql
      dockerfile: postgres.dockerfile
     ports:
      - "5435:5432/tcp"
     environment:
       - POSTGRES_PASSWORD=notkamailio
       - POSTGRES_DB=kamailio
