services:
   kamailio_database:
     build:
      context: ./mariadb
      dockerfile: mariadb.dockerfile
     expose:
      - "3306"
     environment:
       - MARIADB_ROOT_PASSWORD=notkamailio
       - MARIADB_DATABASE=kamailio
       - MARIADB_USER=kamailio
       - MARIADB_PASSWORD=kamailiorw
   asterisk:
     build:
      context: ./asterisk
      dockerfile: asterisk.dockerfile
     deploy:
       mode: replicated
       replicas: 6
   kamailio_dispatcher:
     depends_on:
       - asterisk
       - kamailio_database
     build:
      context: ./kamailio
      dockerfile: kamailio.dockerfile
     ports:
       - "5060:5060/udp"
     links:
       - kamailio_database:kamailio_database
     restart: always
